baseurl = "https://perception-machines.netlify.com"
languageCode = "en-gb"
title = "Perception Machines"
theme = "hpstr-hugo-theme"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "jhooge"

[params]
	subtitle = "Making Sense - Bit by Bit."
	[params.author]
		name = "Jens Hooge"
		avatar = "/images/avatar.jpg"
		bio = "Bioinformatician & Machine Learning Engineer"
		github = "jhooge"
		linkedin = "jenshooge"
		twitter = "HoogeJens"
	[params.image]
	  feature = "/images/image_front.jpg"
	  creditlink = "http://places.csail.mit.edu"
